// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo3y7xloDg9ZF1FKkDzfG_JyjtCDUjxNc',
    appId: '1:1003232898338:web:8e9e72813d7a9d517e497b',
    messagingSenderId: '1003232898338',
    projectId: 'daily-drop-ed693',
    authDomain: 'daily-drop-ed693.firebaseapp.com',
    storageBucket: 'daily-drop-ed693.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA_G2cwk_ghyy9Ti0QrttgAGiNW7GH9s4',
    appId: '1:1003232898338:android:64618c8a80a369d57e497b',
    messagingSenderId: '1003232898338',
    projectId: 'daily-drop-ed693',
    storageBucket: 'daily-drop-ed693.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA5oUOeNzddJrQ6CdC20W8_PlCQt_BT3I',
    appId: '1:1003232898338:ios:6e06a8c79c949d4c7e497b',
    messagingSenderId: '1003232898338',
    projectId: 'daily-drop-ed693',
    storageBucket: 'daily-drop-ed693.firebasestorage.app',
    iosBundleId: 'com.example.dailyDrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA5oUOeNzddJrQ6CdC20W8_PlCQt_BT3I',
    appId: '1:1003232898338:ios:6e06a8c79c949d4c7e497b',
    messagingSenderId: '1003232898338',
    projectId: 'daily-drop-ed693',
    storageBucket: 'daily-drop-ed693.firebasestorage.app',
    iosBundleId: 'com.example.dailyDrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo3y7xloDg9ZF1FKkDzfG_JyjtCDUjxNc',
    appId: '1:1003232898338:web:99f27564761cb6347e497b',
    messagingSenderId: '1003232898338',
    projectId: 'daily-drop-ed693',
    authDomain: 'daily-drop-ed693.firebaseapp.com',
    storageBucket: 'daily-drop-ed693.firebasestorage.app',
  );
}
